from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List, Optional

from .. import crud, schemas, auth, models
from ..database import get_db
from ..services.ai_agent import run_recovery_scenario_generation
from ..services.simulation import run_scenario_simulation
from ..services.sap_adapter import get_sap_adapter

router = APIRouter(prefix="/api/scenarios", tags=["scenarios"])

@router.get("", response_model=List[schemas.ScenarioResponse])
def get_scenarios(
    tariff_event_id: Optional[int] = None,
    current_user: models.User = Depends(auth.get_current_user),
    db: Session = Depends(get_db)
):
    """
    List recovery scenarios. Optional filtering by tariff event.
    """
    return crud.get_scenarios(db, tariff_event_id=tariff_event_id)

@router.get("/{scenario_id}", response_model=schemas.ScenarioResponse)
def get_scenario(
    scenario_id: int,
    current_user: models.User = Depends(auth.get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get a single scenario details.
    """
    scen = crud.get_scenario(db, scenario_id)
    if not scen:
        raise HTTPException(status_code=404, detail="Scenario not found")
    return scen

@router.post("/generate", response_model=List[schemas.ScenarioResponse])
def generate_scenarios(
    event_id: int,
    product_id: str,
    demand_qty: int,
    current_user: models.User = Depends(auth.require_buyer),
    db: Session = Depends(get_db)
):
    """
    Generates alternative recovery plans for a tariff event using LangGraph AI,
    MIP optimization, and deterministic validations. Accessible only by Buyers.
    """
    # 1. Run LangGraph pipeline
    result = run_recovery_scenario_generation(
        db=db,
        event_id=event_id,
        product_id=product_id,
        demand_qty=demand_qty,
        user_org_id=current_user.organization_id
    )
    
    if result["status"] == "ERROR":
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, 
            detail=f"Scenario generation failed: {result.get('error_code')}"
        )
        
    # 2. Save generated scenarios in ARES database
    saved_scenarios = []
    for sc_data in result["scenarios"]:
        # Prepare schemas.ScenarioCreate
        # Extract actions and parse them
        actions_list = []
        for act in sc_data.get("actions", []):
            actions_list.append(schemas.ScenarioAction(
                action_type=act.get("action_type"),
                supplier_org_id=act.get("supplier_org_id"),
                product_id=act.get("product_id"),
                quantity=act.get("quantity"),
                route_id=act.get("route_id"),
                facility_id=act.get("facility_id"),
                cost_impact=act.get("cost_impact", 0.0)
            ))
            
        scen_create = schemas.ScenarioCreate(
            tariff_event_id=event_id,
            name=sc_data.get("name"),
            objective=sc_data.get("objective"),
            action_details=actions_list
        )
        
        db_scen = crud.create_scenario(db, scen_create, created_by=current_user.id)
        
        # Save metrics generated by validation/optimizer
        crud.update_scenario_metrics(
            db,
            scenario_id=db_scen.id,
            feasibility=sc_data.get("feasibility", "FEASIBLE"),
            feasibility_notes=sc_data.get("feasibility_notes", ""),
            cost=sc_data.get("cost", 0.0),
            time_days=sc_data.get("time_days", 0),
            risk=sc_data.get("risk", 0.0),
            continuity=sc_data.get("continuity", 100.0)
        )
        
        db.refresh(db_scen)
        saved_scenarios.append(db_scen)
        
    return saved_scenarios

@router.put("/{scenario_id}/approve", response_model=schemas.ScenarioResponse)
def approve_scenario(
    scenario_id: int,
    payload: schemas.ScenarioApproval,
    current_user: models.User = Depends(auth.require_buyer),
    db: Session = Depends(get_db)
):
    """
    Approve or reject a recovery scenario. Only approved scenarios can run simulation.
    Syncs decision to SAP Integration Suite.
    """
    scen = crud.get_scenario(db, scenario_id)
    if not scen:
        raise HTTPException(status_code=404, detail="Scenario not found")
        
    if payload.status == "APPROVED" and scen.feasibility == "INFEASIBLE":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="Cannot approve an INFEASIBLE recovery plan."
        )

    # 1. Update status
    updated_scen = crud.update_scenario_status(
        db, 
        scenario_id=scenario_id, 
        status=payload.status, 
        auditor_email=current_user.email, 
        auditor_id=current_user.id
    )
    
    if payload.status == "APPROVED":
        # Auto-supersede unapproved sibling scenarios for the same tariff event
        db.query(models.Scenario).filter(
            models.Scenario.tariff_event_id == updated_scen.tariff_event_id,
            models.Scenario.id != scenario_id,
            models.Scenario.status == "PENDING_REVIEW"
        ).update({"status": "SUPERSEDED"}, synchronize_session=False)
        db.commit()

        # 2. Trigger Simulation
        sim_data = run_scenario_simulation(db, updated_scen)
        crud.create_simulation_result(
            db, 
            scenario_id=scenario_id, 
            before_kpi=sim_data["before_kpi"], 
            after_kpi=sim_data["after_kpi"]
        )
        
        # 3. SAP Sync (Mocked PO creation / route override)
        sap = get_sap_adapter()
        sap_payload = []
        for act in updated_scen.action_details:
            sap_payload.append({
                "ScenarioId": scenario_id,
                "ActionType": act.get("action_type"),
                "Product": act.get("product_id"),
                "Supplier": act.get("supplier_org_id"),
                "Quantity": act.get("quantity"),
                "Route": act.get("route_id")
            })
        
        sap.sync_to_sap_analytics("ScenarioApprovals", sap_payload)
        
        # Create SAP purchase orders if reallocated
        for act in updated_scen.action_details:
            if act.get("action_type") in ["INCREASE_ALLOCATION", "SWITCH_SUPPLIER"]:
                crud.log_action(
                    db,
                    action="SAP_PURCHASE_ORDER_TRIGGERED",
                    entity_type="Scenario",
                    entity_id=scenario_id,
                    description=f"Triggered SAP PO for product {act.get('product_id')} to vendor {act.get('supplier_org_id')} for quantity {act.get('quantity')}.",
                    user_id=current_user.id,
                    email=current_user.email
                )

    return updated_scen


@router.post("/clear-pending")
def clear_pending_scenarios(
    current_user: models.User = Depends(auth.require_buyer),
    db: Session = Depends(get_db)
):
    """
    Clear pending candidate scenarios after a mitigation decision has been executed,
    allowing the buyer to start a clean optimization run for the next disruption.
    """
    db.query(models.Scenario).filter(models.Scenario.status == "PENDING_REVIEW").update({"status": "SUPERSEDED"}, synchronize_session=False)
    db.commit()
    return {"message": "Pending scenarios cleared"}


# --- SIMULATION ENDPOINTS ---

@router.get("/{scenario_id}/simulation", response_model=List[schemas.SimulationResponse])
def get_scenario_simulation(
    scenario_id: int,
    current_user: models.User = Depends(auth.get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get the simulation results (KPI comparison) for an approved scenario.
    """
    results = crud.get_simulation_results(db, scenario_id=scenario_id)
    return results
