"""Add SupplierNotification table

Revision ID: 2e5df44913d7
Revises: c9eada6e15f1
Create Date: 2026-09-01 18:59:39.002796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5df44913d7'
down_revision: Union[str, Sequence[str], None] = 'c9eada6e15f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_org_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_notifications_id'), 'supplier_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_notifications_supplier_org_id'), 'supplier_notifications', ['supplier_org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_supplier_notifications_supplier_org_id'), table_name='supplier_notifications')
    op.drop_index(op.f('ix_supplier_notifications_id'), table_name='supplier_notifications')
    op.drop_table('supplier_notifications')
    # ### end Alembic commands ###
