"""Add supplier_org_id to Route

Revision ID: e3e6de96c90f
Revises: 2e5df44913d7
Create Date: 2026-09-01 19:08:56.921715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e6de96c90f'
down_revision: Union[str, Sequence[str], None] = '2e5df44913d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes') as batch_op:
        batch_op.create_foreign_key('fk_routes_organizations', 'organizations', ['supplier_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes') as batch_op:
        batch_op.drop_constraint('fk_routes_organizations', type_='foreignkey')
    # ### end Alembic commands ###
